# Generated by Django 3.2 on 2022-06-10 16:52

from django.db import migrations, models
import django.db.models.deletion
import prints.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('display_name', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to=prints.models.product_upload_path)),
                ('description', models.TextField()),
                ('variant_type', models.CharField(choices=[('CL', 'Colours'), ('SZ', 'Sizes')], default='SZ', max_length=2)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prints.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('display_name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to=prints.models.variant_upload_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sku', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prints.product')),
            ],
        ),
    ]
