# Generated by Django 3.2 on 2022-06-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'name'), ('product', 'display_name')},
        ),
    ]
