# Generated by Django 3.2 on 2022-06-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_alter_productvariant_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='cost',
            new_name='price',
        ),
    ]
